name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  BUCKET_NAME : "chris-sa-portfolio"
  AWS_REGION : "ap-southeast-2"

permissions:
    id-token: write
    contents: read

jobs:
  Build-and-upload-S3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'

      - name: Build
        run: cd main && npm ci && npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::618566478002:role/GithubActionPortfolioDeploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 sync ./main/dist s3://${{ env.BUCKET_NAME }}/ --delete --quiet
        
      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths '/*'
