name: Build and Deploy

on:
  push:
    branches: [ dev ]

env:
  BUCKET_NAME : "dev-chris-sa-portfolio"
  AWS_REGION : "ap-southeast-2"

permissions:
    id-token: write
    contents: read

jobs:
  Build-and-upload-S3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Build
        run: cd main && npm ci && npm run build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::618566478002:role/GithubActionDevPortfolio
          aws-region: ${{ env.AWS_REGION }}
      - name: Upload to S3
        run: aws s3 sync ./main/build s3://${{ env.BUCKET_NAME }}/ --delete
